import type { NextPage } from "next";
import Head from "next/head";
import App from "../src/App";
import styles from "./Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>ReposEye</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="#">ReposEye!</a>
        </h1>
        <App />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
